export interface Speaker {
  name: string;
  company: string;
  image: string;
  xLink?: string;
  imageScale?: string;
}

export const pastSpeakers: Speaker[] = [
  {
    name: "Abhishek Yadav",
    company: "Etherspot",
    image: "/assets/speakers/Abhishek Yadav - Etherspot.png",
    xLink: "https://x.com/abhixh",
    imageScale: "h-[150%]",
  },
  {
    name: "Aditi Polkam",
    company: "Offline Protocol",
    image: "/assets/speakers/Aditi_Polkam.png",
    xLink: "https://x.com//aditipolkam",
    imageScale: "h-[185%]",
  },
  {
    name: "Aniket Sharma",
    company: "Rath Finance",
    image: "/assets/speakers/Aniket Sharma - Rath Finance.png",
    xLink: "https://x.com/0xaniketsharma",
    imageScale: "h-[110%]",
  },
  {
    name: "Ayush Bhadauria",
    company: "ZisK",
    image: "/assets/speakers/Ayush Bhadauria - ZisK.png",
    xLink: "https://x.com/0xAbix",
    imageScale: "h-[140%]",
  },
  {
    name: "Ayush Bherwani",
    company: "MetaMask",
    image: "/assets/speakers/Ayush_Bherwani.png",
    xLink: "http://x.com/ayushbherwani",
    imageScale: "h-[120%]",
  },
  {
    name: "Denver Dsouza",
    company: "Devfolio",
    image: "/assets/speakers/Denver Dsouza - Devfolio.png",
    xLink: "https://x.com/denverjude",
    imageScale: "h-[130%]",
  },
  {
    name: "Dhaiwat",
    company: "",
    image: "/assets/speakers/dhaiwat.png",
    xLink: "https://x.com/dhaiwat10",
    imageScale: "h-[145%]",
  },
  {
    name: "Jatin Pandya",
    company: "",
    image: "/assets/speakers/Jatin_Pandya.png",
    xLink: "https://twitter.com/Jpandya26",
    imageScale: "h-[185%]",
  },
  {
    name: "Kanika Mishra",
    company: "USDT Marketplace",
    image: "/assets/speakers/Kanika_Mishra.png",
    xLink: "https://x.com/mishrakanika3",
    imageScale: "h-[140%]",
  },
  {
    name: "Krishang Shah",
    company: "Polygon Labs",
    image: "/assets/speakers/Krishang_Shah.png",
    xLink: "https://x.com/0xkrishang",
    imageScale: "h-[130%]",
  },
  {
    name: "Kunal Gandhi",
    company: "HeyElsa",
    image: "/assets/hackathon/judges/kunal_gandhi-removebg-preview.png",
    xLink: "https://x.com/kunalvg",
    imageScale: "h-[120%] right-[50%]",
  },
  {
    name: "Nandit Mehra",
    company: "Lighthouse",
    image: "/assets/hackathon/judges/Nandit_Judge-removebg-preview.png",
    xLink: "https://x.com/nanditmehra",
    imageScale: "h-[120%]",
  },
  {
    name: "Pareen Lathia",
    company: "Monad Foundation",
    image: "/assets/speakers/Pareen_Lathai.png",
    xLink: "https://x.com/pareen",
  },
  {
    name: "Rahat",
    company: "Move Industries",
    image: "/assets/speakers/Rahat.png",
    xLink: "https://x.com/Rahatcodes",
    imageScale: "h-[145%]",
  },
  {
    name: "Rahul Bhadoriya",
    company: "Dacoit",
    image: "/assets/speakers/Rahul_Bhadoriya.png",
    xLink: "https://x.com/rahulbhadoriya",
    imageScale: "h-[130%]",
  },
  {
    name: "Sahil Sen",
    company: "Quicknode",
    image: "/assets/speakers/Sahil_Sen_-_Quicknode-removebg-preview.png",
    xLink: "https://x.com/sensahil",
    imageScale: "h-[125%]",
  },
  {
    name: "Sebastian Burkhard",
    company: "Yodl Pay",
    image: "/assets/speakers/Sebastian_Burkhard.png",
    xLink: "https://x.com/yodl_meister",
    imageScale: "h-[120%]",
  },
  {
    name: "Shiv Bhonde ",
    company: "BuidlGuidl",
    image: "/assets/speakers/Shiv_Bhonde.png",
    xLink: "https://x.com/ShivBhonde",
    imageScale: "h-[128%]",
  },
  {
    name: "Shyam Sridhar",
    company: "Ethereum Foundation",
    image: "/assets/speakers/Shyam_Sridhar2.png",
    xLink: "https://x.com/ShyamSridhar7",
    imageScale: "h-[130%]",
  },
  {
    name: "Siddharth Biju",
    company: "",
    image: "/assets/speakers/Siddharth Biju.png",
    xLink: "https://x.com/sidbharth",
    imageScale: "h-[120%]",
  },
  {
    name: "Smit Khakhkhar",
    company: "CoinList",
    image: "/assets/hackathon/judges/Smit_Judge-removebg-preview.png",
    xLink: "https://x.com/0xSmit",
    imageScale: "h-[110%]",
  },
];

export const homeSpeakers: Speaker[] = [
  {
    name: "Aditi Polkam",
    company: "Offline Protocol",
    image: "/assets/speakers/Aditi_Polkam.png",
    xLink: "https://x.com//aditipolkam",
    imageScale: "h-[185%]",
  },
  {
    name: "Ayush Bherwani",
    company: "MetaMask",
    image: "/assets/speakers/Ayush_Bherwani.png",
    xLink: "http://x.com/ayushbherwani",
    imageScale: "h-[120%]",
  },
  {
    name: "Dhaiwat",
    company: "",
    image: "/assets/speakers/dhaiwat.png",
    xLink: "https://x.com/dhaiwat10",
    imageScale: "h-[145%]",
  },
  {
    name: "Jatin Pandya",
    company: "",
    image: "/assets/speakers/Jatin_Pandya.png",
    xLink: "https://twitter.com/Jpandya26",
    imageScale: "h-[185%]",
  },
  {
    name: "Kanika Mishra",
    company: "USDT Marketplace",
    image: "/assets/speakers/Kanika_Mishra.png",
    xLink: "https://x.com/mishrakanika3",
    imageScale: "h-[140%]",
  },
  {
    name: "Krishang Shah",
    company: "Polygon Labs",
    image: "/assets/speakers/Krishang_Shah.png",
    xLink: "https://x.com/0xkrishang",
    imageScale: "h-[130%]",
  },
  {
    name: "Pareen Lathia",
    company: "Monad Foundation",
    image: "/assets/speakers/Pareen_Lathai.png",
    xLink: "https://x.com/pareen",
  },
  {
    name: "Rahat",
    company: "Move Industries",
    image: "/assets/speakers/Rahat.png",
    xLink: "https://x.com/Rahatcodes",
    imageScale: "h-[145%]",
  },
  {
    name: "Rahul Bhadoriya",
    company: "Dacoit",
    image: "/assets/speakers/Rahul_Bhadoriya.png",
    xLink: "https://x.com/rahulbhadoriya",
    imageScale: "h-[130%]",
  },
  {
    name: "Sebastian Burkhard",
    company: "Yodl Pay",
    image: "/assets/speakers/Sebastian_Burkhard.png",
    xLink: "https://x.com/yodl_meister",
    imageScale: "h-[120%]",
  },
  {
    name: "Shiv Bhonde ",
    company: "BuidlGuidl",
    image: "/assets/speakers/Shiv_Bhonde.png",
    xLink: "https://x.com/ShivBhonde",
    imageScale: "h-[128%]",
  },
  {
    name: "Shyam Sridhar",
    company: "Ethereum Foundation",
    image: "/assets/speakers/Shyam_Sridhar2.png",
    xLink: "https://x.com/ShyamSridhar7",
    imageScale: "h-[130%]",
  },
];
export const conferenceSpeakers: Speaker[] = [
  {
    name: "Abhishek Yadav",
    company: "Etherspot",
    image: "/assets/speakers/Abhishek Yadav - Etherspot.png",
    xLink: "https://x.com/abhixh",
    imageScale: "h-[150%]",
  },
  {
    name: "Aditi Polkam",
    company: "Offline Protocol",
    image: "/assets/speakers/Aditi_Polkam.png",
    xLink: "https://x.com//aditipolkam",
    imageScale: "h-[185%]",
  },
  {
    name: "Aniket Sharma",
    company: "Rath Finance",
    image: "/assets/speakers/Aniket Sharma - Rath Finance.png",
    xLink: "https://x.com/0xaniketsharma",
    imageScale: "h-[110%]",
  },
  {
    name: "Ayush Bhadauria",
    company: "ZisK",
    image: "/assets/speakers/Ayush Bhadauria - ZisK.png",
    xLink: "https://x.com/0xAbix",
    imageScale: "h-[140%]",
  },
  {
    name: "Ayush Bherwani",
    company: "MetaMask",
    image: "/assets/speakers/Ayush_Bherwani.png",
    xLink: "http://x.com/ayushbherwani",
    imageScale: "h-[120%]",
  },
  {
    name: "Denver Dsouza",
    company: "Devfolio",
    image: "/assets/speakers/Denver Dsouza - Devfolio.png",
    xLink: "https://x.com/denverjude",
    imageScale: "h-[130%]",
  },
  {
    name: "Dhaiwat",
    company: "",
    image: "/assets/speakers/dhaiwat.png",
    xLink: "https://x.com/dhaiwat10",
    imageScale: "h-[145%]",
  },
  {
    name: "Jatin Pandya",
    company: "",
    image: "/assets/speakers/Jatin_Pandya.png",
    xLink: "https://twitter.com/Jpandya26",
    imageScale: "h-[185%]",
  },
  {
    name: "Kanika Mishra",
    company: "USDT Marketplace",
    image: "/assets/speakers/Kanika_Mishra.png",
    xLink: "https://x.com/mishrakanika3",
    imageScale: "h-[140%]",
  },
  {
    name: "Krishang Shah",
    company: "Polygon Labs",
    image: "/assets/speakers/Krishang_Shah.png",
    xLink: "https://x.com/0xkrishang",
    imageScale: "h-[130%]",
  },
  {
    name: "Pareen Lathia",
    company: "Monad Foundation",
    image: "/assets/speakers/Pareen_Lathai.png",
    xLink: "https://x.com/pareen",
  },
  {
    name: "Rahat",
    company: "Move Industries",
    image: "/assets/speakers/Rahat.png",
    xLink: "https://x.com/Rahatcodes",
    imageScale: "h-[145%]",
  },
  {
    name: "Rahul Bhadoriya",
    company: "Dacoit",
    image: "/assets/speakers/Rahul_Bhadoriya.png",
    xLink: "https://x.com/rahulbhadoriya",
    imageScale: "h-[130%]",
  },
  {
    name: "Sahil Sen",
    company: "Quicknode",
    image: "/assets/speakers/Sahil_Sen_-_Quicknode-removebg-preview.png",
    xLink: "https://x.com/sensahil",
    imageScale: "h-[125%]",
  },
  {
    name: "Sebastian Burkhard",
    company: "Yodl Pay",
    image: "/assets/speakers/Sebastian_Burkhard.png",
    xLink: "https://x.com/yodl_meister",
    imageScale: "h-[120%]",
  },
  {
    name: "Shiv Bhonde ",
    company: "BuidlGuidl",
    image: "/assets/speakers/Shiv_Bhonde.png",
    xLink: "https://x.com/ShivBhonde",
    imageScale: "h-[128%]",
  },
  {
    name: "Shyam Sridhar",
    company: "Ethereum Foundation",
    image: "/assets/speakers/Shyam_Sridhar2.png",
    xLink: "https://x.com/ShyamSridhar7",
    imageScale: "h-[130%]",
  },
  {
    name: "Siddharth Biju",
    company: "",
    image: "/assets/speakers/Siddharth Biju.png",
    xLink: "https://x.com/sidbharth",
    imageScale: "h-[120%]",
  },
];
